"""Added initial tables

Revision ID: d2d1291df330
Revises: 
Create Date: 2025-08-12 16:44:47.928891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2d1291df330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_name')
    )
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('cash_flow',
    sa.Column('cash_flow_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('flow_date', sa.Date(), nullable=False),
    sa.Column('flow_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('cash_flow_id')
    )
    op.create_table('investments',
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('investment_type', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('investment_id')
    )
    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('portfolio_id'),
    sa.UniqueConstraint('portfolio_name')
    )
    op.create_table('substrides',
    sa.Column('substride_id', sa.Integer(), nullable=False),
    sa.Column('substride_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('substride_id')
    )
    op.create_table('wallets',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('wallet_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_table('portfolio_investments',
    sa.Column('portfolio_investment_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('allocated_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.investment_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('portfolio_investment_id'),
    sa.UniqueConstraint('portfolio_id', 'investment_id', name='_portfolio_investment_uc')
    )
    op.create_table('purchases',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_purchased', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_purchase_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.investment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_sold', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_sale_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gain_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.investment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.investment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.drop_table('gl_table')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'user'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'user'"))

    op.create_table('gl_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Date', sa.DATE(), nullable=False),
    sa.Column('Account_Code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Account', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Amount_in_Currency', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('Credit', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Debit', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Label', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Partner', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Analytic_lines_Amount', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Analytic_lines_Department', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_Employees', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_HO', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_Inter_companies', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_Investment_At_Cost', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Analytic_lines_Investment_At_FV', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Analytic_lines_Investment_At_OCI', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Analytic_lines_Investment_In_Fund', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_Project_Location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_Projects', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_Qaysirayah', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_RTS', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_Shareholders', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Analytic_lines_Trading', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('transactions')
    op.drop_table('sales')
    op.drop_table('purchases')
    op.drop_table('portfolio_investments')
    op.drop_table('wallets')
    op.drop_table('substrides')
    op.drop_table('portfolios')
    op.drop_table('investments')
    op.drop_table('cash_flow')
    op.drop_table('companies')
    op.drop_table('chart_of_accounts')
    # ### end Alembic commands ###
